#!/usr/bin/env python3

"""
中文说明：
- 文件路径：`tools/openmoss/control_center/paths.py`
- 文件作用：负责控制中心中与 `paths` 相关的编排、分析或决策逻辑。
- 顶层函数：无顶层函数。
- 顶层类：无顶层类。
- 阅读建议：先看模块说明，再按函数/类 docstring 顺着主流程理解调用关系。
"""
from __future__ import annotations

from pathlib import Path


WORKSPACE_ROOT = Path("/Users/mac_claw/.openclaw/workspace")
OPENMOSS_ROOT = WORKSPACE_ROOT / "tools/openmoss"
CONTROL_CENTER_ROOT = OPENMOSS_ROOT / "control_center"
AUTONOMY_ROOT = OPENMOSS_ROOT / "autonomy"
BRIDGE_ROOT = OPENMOSS_ROOT / "bridge"
RUNTIME_ROOT = OPENMOSS_ROOT / "runtime"
CONTROL_CENTER_RUNTIME_ROOT = RUNTIME_ROOT / "control_center"
APPROVALS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "approvals"
MISSIONS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "missions"
CACHE_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "cache"
SUMMARIES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "summaries"
ADVISORIES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "advisories"
RESEARCH_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "research"
TOOL_SCORES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "tool_scores"
RESELECTIONS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "reselections"
ADOPTIONS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "adoptions"
DOMAIN_PROFILES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "domain_profiles"
FETCH_ROUTES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "fetch_routes"
CHALLENGES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "challenges"
AUTHORIZED_SESSIONS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "authorized_sessions"
HUMAN_CHECKPOINTS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "human_checkpoints"
EVENTS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "events"
HOOKS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "hooks"
GOVERNANCE_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "governance"
POLICY_ROOT = GOVERNANCE_ROOT / "policy"
MEMORY_ROOT = GOVERNANCE_ROOT / "memory"
MEMORY_PIPELINES_ROOT = MEMORY_ROOT / "pipelines"
MEMORY_PROJECT_INDEX_PATH = MEMORY_ROOT / "project_index.json"
MEMORY_WRITEBACK_ROOT = MEMORY_ROOT / "writebacks"
BRAIN_ROUTES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "brain_routes"
BRAIN_RECEIPTS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "brain_receipts"
BROWSER_SIGNALS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "browser_signals"
BROWSER_CHANNELS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "browser_channels"
TASK_STATUS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "task_status"
CONTRACT_QUARANTINE_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "contract_quarantine"
CONTROL_PLANE_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "control_plane"
PROCESS_REGISTRY_PATH = CONTROL_PLANE_ROOT / "process_registry.json"
TASK_REGISTRY_PATH = CONTROL_PLANE_ROOT / "task_registry.json"
WAITING_REGISTRY_PATH = CONTROL_PLANE_ROOT / "waiting_registry.json"
DOCTOR_QUEUE_PATH = CONTROL_PLANE_ROOT / "doctor_queue.json"
ALERTS_PATH = CONTROL_PLANE_ROOT / "alerts.json"
SYSTEM_SNAPSHOT_PATH = CONTROL_PLANE_ROOT / "system_snapshot.json"
DOCTOR_LAST_RUN_PATH = CONTROL_CENTER_RUNTIME_ROOT / "doctor" / "last_run.json"
CRAWLER_CAPABILITY_PROFILE_PATH = CONTROL_PLANE_ROOT / "crawler_capability_profile.json"
CRAWLER_CAPABILITY_HISTORY_PATH = CONTROL_PLANE_ROOT / "crawler_capability_history.json"
CRAWLER_REMEDIATION_QUEUE_PATH = CONTROL_PLANE_ROOT / "crawler_remediation_queue.json"
CRAWLER_REMEDIATION_PLAN_PATH = CONTROL_PLANE_ROOT / "crawler_remediation_plan.json"
CRAWLER_REMEDIATION_EXECUTION_PATH = CONTROL_PLANE_ROOT / "crawler_remediation_execution.json"
CRAWLER_REMEDIATION_SCHEDULER_STATE_PATH = CONTROL_PLANE_ROOT / "crawler_remediation_scheduler_state.json"
SELLER_BULK_SCHEDULER_STATE_PATH = CONTROL_PLANE_ROOT / "seller_bulk_scheduler_state.json"
CROSS_MARKET_ARBITRAGE_SCHEDULER_STATE_PATH = CONTROL_PLANE_ROOT / "cross_market_arbitrage_scheduler_state.json"
PROJECT_RESULT_FEEDBACK_HISTORY_PATH = CONTROL_PLANE_ROOT / "project_result_feedback_history.json"
PROJECT_REPAIR_VALUE_HISTORY_PATH = CONTROL_PLANE_ROOT / "project_repair_value_history.json"
CAPABILITY_CLONES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "capability_clones"
PROMOTED_CAPABILITIES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "promoted_capabilities"
GENERATED_CAPABILITIES_ROOT = OPENMOSS_ROOT / "generated_capabilities"
SKILLS_ROOT = WORKSPACE_ROOT / "skills"
TOOLS_ROOT = WORKSPACE_ROOT / "tools"
DATA_ROOT = WORKSPACE_ROOT / "data"
OUTPUT_ROOT = WORKSPACE_ROOT / "output"
OPENCLAW_ROOT = Path("/Users/mac_claw/.openclaw")
OPENCLAW_SESSIONS_ROOT = OPENCLAW_ROOT / "agents/main/sessions"
