#!/usr/bin/env python3

from __future__ import annotations

from pathlib import Path


WORKSPACE_ROOT = Path("/Users/mac_claw/.openclaw/workspace")
OPENMOSS_ROOT = WORKSPACE_ROOT / "tools/openmoss"
CONTROL_CENTER_ROOT = OPENMOSS_ROOT / "control_center"
AUTONOMY_ROOT = OPENMOSS_ROOT / "autonomy"
BRIDGE_ROOT = OPENMOSS_ROOT / "bridge"
RUNTIME_ROOT = OPENMOSS_ROOT / "runtime"
CONTROL_CENTER_RUNTIME_ROOT = RUNTIME_ROOT / "control_center"
APPROVALS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "approvals"
MISSIONS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "missions"
CACHE_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "cache"
SUMMARIES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "summaries"
ADVISORIES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "advisories"
RESEARCH_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "research"
TOOL_SCORES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "tool_scores"
RESELECTIONS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "reselections"
ADOPTIONS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "adoptions"
DOMAIN_PROFILES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "domain_profiles"
FETCH_ROUTES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "fetch_routes"
CHALLENGES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "challenges"
AUTHORIZED_SESSIONS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "authorized_sessions"
HUMAN_CHECKPOINTS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "human_checkpoints"
EVENTS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "events"
HOOKS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "hooks"
BRAIN_ROUTES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "brain_routes"
BROWSER_SIGNALS_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "browser_signals"
CAPABILITY_CLONES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "capability_clones"
PROMOTED_CAPABILITIES_ROOT = CONTROL_CENTER_RUNTIME_ROOT / "promoted_capabilities"
GENERATED_CAPABILITIES_ROOT = OPENMOSS_ROOT / "generated_capabilities"
SKILLS_ROOT = WORKSPACE_ROOT / "skills"
TOOLS_ROOT = WORKSPACE_ROOT / "tools"
DATA_ROOT = WORKSPACE_ROOT / "data"
OUTPUT_ROOT = WORKSPACE_ROOT / "output"
OPENCLAW_ROOT = Path("/Users/mac_claw/.openclaw")
OPENCLAW_SESSIONS_ROOT = OPENCLAW_ROOT / "agents/main/sessions"
